name: testes
on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  teste_back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: |
          cd src/findriver/back
          npm ci
      - run: |
          cd src/findriver/back
          npm test
  
  teste_front:
    needs: teste_back
    runs-on: ubuntu-latest
    if: ${{ needs.teste_back.result == 'success' }}
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: |
          cd src/findriver/front
          npm install
      - run: |
          cd src/findriver/front
          npm test
